### ISSUE TITLE
Custom timeout

### ISSUE THREAD

**Issue by Xapphire13** [steelbrain/jasmine-fix#3]
I was wondering if there is a reason you chose not to expose the passing in of a timeout duration and instead [hard coded](https://github.com/steelbrain/jasmine-fix/blob/master/index.js#L10) 10 seconds. It would be an easy change that would also be backward compatible with the current version.

Wanted to ask before I acted upon making a PR.

Thanks

**Comment by steelbrain** [comment]
Sounds good, I'd accept a PR for that

**Comment by steelbrain** [comment]
Thank you for working on this @Xapphire13 

It's been added in v1.2.0
