### ISSUE TITLE
Restore default Date.now

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/jasmine-fix#6]
Jasmine apparently mocks `Date.now()`, which causes some things (like `TextBuffer::onDidReload`) to break, should the restoration of the default function be added here?

See https://github.com/AtomLinter/linter-eslint/pull/981 and the related issues for more details.

**Comment by steelbrain** [comment]
Yes, I would say it should be

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/jasmine-fix/commit/ec4a1e14e057e6c1926b506ae64878b7dca8aa5f
